language: node_js
node_js:
- 5.5.0
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJHQOXBM7NISPC5JA
  secret_access_key:
    secure: secure
  region: eu-west-1
  app: dndapi
  env: dndapi-test
  bucket_name: elasticbeanstalk-eu-west-1-868723413534
  on:
    branch: test
env:
  global:
    secure: RIzkRRTHDlpbkT2L8vHdFbtKx1h6CX8lSKArqLdS8l57F8bEVa6c/J+I3WHUYHR+ibJnzN3SiSgZfAz2cnQKbVaXRQHownzI54zFnkzTw2QVIqNn8e69WOBhJnKqEZVyJjZIMPQrTbIN1rlRaVoYUm3OfQH2K+KsHnkc7xIeQmxdxG390fXpmefq+WxESbv14030jx4MKO3FLso4gTmz4NT6TNWlM0v3F+qQcWzVWZIxh1z7bkwU/V+fQT0a4IkJRoDIgU5dvNg3na2KR/LYRW9NrNH9vCczKk9sJbjwARx+RlbgcZZzLYPWFJKFyPxux6cmgQHnZU8JITNx/WN4R9MMih3XZKEcfQJV4b1A4p6Pm/ycaUZU9oFJjH1UlTO8EHATc12eiWumLn7MP9aYNaZ1gw07kkV9NxrO7ixzQC2aFIhPlYSO6ps99TRGeKQ2j/JQ13W5oEJ1QgFr4zv5I49OmyhTs4z6vLMZD1qhAfbB4o0+kJUUfer7rtmuRlwjBCfv+GLy8b6L0DCgunRMP5jxuUnboWz298x6lX7w59tlWtR4aNzZRz6G0n2ThVTgZDWzl+Nmusbb/O/C1jDwIc+XwM8lxkZmnVdiYQUYavo5MqQ6U9hzuercNenorZ0dMlKQDOVuoq6uCzU1TPn2iPcjbCQrjtBNtcwvmKgAFDY=
