language: node_js
node_js:
  - "5.5.0"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIG3GNNT5I2X47UQQ
  secret_access_key:
    secure: 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
  region: eu-west-1
  app: dndapi-test
  env: dndapi
  bucket_name: elasticbeanstalk-eu-west-1-868723413534
  on:    
    branch: test